# Generated by Django 4.1.2 on 2022-10-19 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.item'),
            preserve_default=False,
        ),
    ]
